apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: my-atlas-cluster
  labels:
    app.kubernetes.io/version: 1.6.0
spec:
  projectRef:
    name: my-project
  deploymentSpec:
    name: "Test-cluster"
    tags:
     - key: "environment"
       value: "production"
    providerSettings:
      instanceSizeName: M10
      providerName: AWS
      regionName: US_EAST_1